### ISSUE TITLE
moc parameter order

### ISSUE THREAD

**Issue by hatcat** [dcourtois/premake-qt#11]
I am using this extension as part of the Total War build system, and I find that the order of the moc parameters is different from that suggested by the moc tool (qt 5.7.0). In a couple of situations this has proven to be non-trivial, resulting in non-building projects. I've made a simple fix to resolve this: is there something I have overlooked or would you be interested in a pull request?

**Comment by dcourtois** [comment]
Hmmm, I can't really tell if you have overlooked something or not since I have no idea what's wrong and what you did to fix it :D

More seriously, do not hesitate to make a pull request ! I'll review it, and when we're both ok with it, I'll gladly accept it :)

(in the meantime I'm going to go check the doc for moc tool to try understand what I'm doing wrong)

**Comment by dcourtois** [comment]
Hi again ! I don't really understand what you're referring to when saying "the order of the moc parameters is different from that suggested by the moc tool" : I'm generating the moc command using command line options (such as -d for defines, -I for include paths, etc.) so the order should be irrelevant ?

Is it a problem with additional options that you're passing through `qtmocargs` that are creating the problem ? (maybe the options you're passing need to be added before the defines, includes, etc. ?)

**Comment by hatcat** [comment]
Ignore me. It turned out to be an overflowing command buffer. Windows is so... small minded...?

**Comment by dcourtois** [comment]
Ok, closing the issue, thanks !
