### ISSUE TITLE
Dealing with too many parameters

### ISSUE THREAD

**Issue by hatcat** [dcourtois/premake-qt#12]
It is possible to pass sufficient parameters to moc such that Windows has insufficient space for them all in the command buffer, truncating it. Fortunately, moc can take an options file as a parameter, which is the obvious solution to this problem. What needs to be done is to modify

premake.extensions.qt.addMOCCustomBuildRule(fcfg, cfg)

to create an output filename, e.g.

local opt = qt.getGeneratedDir(cfg) .. "/moc_" .. fcfg.basename .. ".opt"

and write the options to that file, then modify the command line to take that filename.

Would it be acceptable to make this the default behaviour or should it be on a flag? For the time being I would make it default: I can't think of a reason NOT to do that other than ease of inspection, which militates against the point of premake anyway.

**Comment by dcourtois** [comment]
I don't really like the idea of having to always write files, especially when it's done only to fix the shortcomings of 1 single OS. Also, even if negligible, this introduces a slight overhead each time moc is run (disk read access to load the flags from the file)

At the very least, I would generate files only on Windows. And ideally, if the size limit for command line arguments is officially documented, the perfect way would be to get the size of the command line, and if it's greater than this limit, use a file, otherwise keep the current behavior.

I'll have a look at this

**Comment by dcourtois** [comment]
Ok, this information was easier to find than I anticipated: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd--exe-command-line-string-limitation

So, this seems to be a limitation which is on XP only, and this limit is 8192 characters.
I'm willing to handle this case, but I must say as a developer: if your moc command line is greater than 8192, maybe something should be done on your build system too :p (weel, sometimes it's not possible, I've been there too :p)

**Comment by hatcat** [comment]
Hmmmm... I have implemented a full and flexible solution so hold your fire; i’m back in the studio on Tuesday and I’ll make a pull request. However, i’m passing <1K characters, so I wonder if there’s another problem I need to solve.

**Comment by hatcat** [comment]
(By which I mean it’s on a flag with a parameter for the options file directory)

**Comment by dcourtois** [comment]
Ok, I'll wait for the PR then (was mostly done with my implementation, but since I'm on Linux currently, I prefer using your tested implementation :)

But if you're sending less than 1k chars, that's a bit strange ... did you try executing the command directly in a shell ?

Also, I'm in vacation at the end of the day for 1 week, so the review and integration will have to wait until my return, sorry.

**Comment by dcourtois** [comment]
Hi again,

I'm back from holidays. Since you didn't send any request, I took the liberty to finalize my own fix. There is now a command `qtcommandlinesizelimit` which takes the max number of characters supported by the command line. By default, on Windows it's 2047. This command applies to the current configuration scope, so you can use it only on Windows, or on all platforms, configs, etc.

When a moc command line exceed this limit, the generated command is of the form 
`moc <input> -o <output> -b <pch> @<the_rest_of_the_args>`

(-b doesn't seem to be supported in the @ file)

Closing the issue now, but do not hesitate to re-open it (or open a new one) if this doesn't work, if you need more options.
